### ISSUE TITLE
what was the rewrite "lively4-server/server.js" about?

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively4-server#5]
was it a rewrite / alternative implementation?
Why did it not replace httpServer in the first place?

@jgraichen

**Comment by jgraichen** [comment]
That is a rewrite using techniques from the the service worker. I've used Bluebird coroutines for easy asynchronous flow, like async/await (unfortunately not directly supported by node), fully async filesystem IO and fixed a few things with CORS and CORS preflight requests.

**Comment by jgraichen** [comment]
If I remember correctly it also fixed a few things with shadowing like deleted files/

**Comment by JensLincke** [comment]
moved to branch and deleted in master
